In [11]:
import numpy as np
import pandas as pd

In [12]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [13]:
temp_df = temp_df.head(10000)

In [14]:
temp_df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [15]:
temp_df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [16]:
temp_df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [17]:
temp_df.duplicated().sum()

17

In [18]:
temp_df.drop_duplicates(inplace=True)

In [19]:
temp_df.duplicated().sum()

0

In [20]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [21]:
temp_df['review'] = temp_df['review'].apply(remove_tags)

In [22]:
temp_df.review[12]

'So im not a big fan of Boll\'s work but then again not many are. I enjoyed his movie Postal (maybe im the only one). Boll apparently bought the rights to use Far Cry long ago even before the game itself was even finsished. People who have enjoyed killing mercs and infiltrating secret research labs located on a tropical island should be warned, that this is not Far Cry... This is something Mr Boll have schemed together along with his legion of schmucks.. Feeling loneley on the set Mr Boll invites three of his countrymen to play with. These players go by the names of Til Schweiger, Udo Kier and Ralf Moeller.Three names that actually have made them selfs pretty big in the movie biz. So the tale goes like this, Jack Carver played by Til Schweiger (yes Carver is German all hail the bratwurst eating dudes!!) However I find that Tils acting in this movie is pretty badass.. People have complained about how he\'s not really staying true to the whole Carver agenda but we only saw carver in a fi

In [23]:
temp_df['review'] = temp_df['review'].apply(lambda x:x.lower())

In [24]:
temp_df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [25]:
temp_df.review[1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [26]:
import nltk
from nltk.corpus import stopwords
 
nltk.download('stopwords')

sw_list = stopwords.words('english')
print(sw_list)

temp_df['review'] = temp_df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to C:\Users\YOU TECH
[nltk_data]     BD\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [27]:
temp_df.review[1]

'wonderful little production. filming technique unassuming- old-time-bbc fashion gives comforting, sometimes discomforting, sense realism entire piece. actors extremely well chosen- michael sheen "has got polari" voices pat too! truly see seamless editing guided references williams\' diary entries, well worth watching terrificly written performed piece. masterful production one great master\'s comedy life. realism really comes home little things: fantasy guard which, rather use traditional \'dream\' techniques remains solid disappears. plays knowledge senses, particularly scenes concerning orton halliwell sets (particularly flat halliwell\'s murals decorating every surface) terribly well done.'

In [28]:
X = temp_df.iloc[:,0:1]

In [29]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [30]:
y = temp_df['sentiment']

In [31]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [32]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [34]:
print(len(X_train))
print(len(X_test))
X_train.shape

7986
1997


(7986, 1)

In [35]:
#Applying Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [36]:
X_train_bow.shape

(7986, 48282)

In [37]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [38]:
y_pred = gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [39]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]], dtype=int64)

In [40]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8437656484727091

In [41]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8407611417125689

In [42]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8417626439659489

In [43]:
#Using TfIdf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [44]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8452679018527791

In [45]:
#Applying Word2Vec
import gensim

In [56]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt')


[nltk_data] Downloading package punkt to C:\Users\YOU TECH
[nltk_data]     BD\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [58]:
story = []
for doc in temp_df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [60]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)
model.build_vocab(story)
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5875669, 6212140)

In [61]:
len(model.wv.index_to_key)

31845

In [62]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [64]:
document_vector(temp_df['review'].values[0])

array([-0.16060837,  0.49697965,  0.21094511,  0.21620795, -0.09066404,
       -0.5966556 ,  0.20496441,  0.98180026, -0.3727723 , -0.28643313,
       -0.25008938, -0.4599054 ,  0.15242234,  0.15494068,  0.177519  ,
       -0.12425805,  0.01473496, -0.3177695 , -0.08079779, -0.6837773 ,
        0.03271278,  0.18842454,  0.07308728, -0.26454476, -0.3492893 ,
       -0.05273095, -0.26304245,  0.02376967, -0.2836608 ,  0.0991938 ,
        0.30097613, -0.00994897,  0.23316407, -0.30376258, -0.1666632 ,
        0.33084372,  0.0502637 , -0.33516786, -0.20764184, -0.796477  ,
        0.16537774, -0.23535657, -0.01651777, -0.08078538,  0.4233436 ,
       -0.13322029, -0.22406593, -0.0334495 ,  0.0962736 ,  0.37419188,
        0.03356032, -0.36055067, -0.46279123, -0.14789927, -0.06174221,
        0.2873573 ,  0.20386493,  0.02867124, -0.2839419 ,  0.05940871,
        0.02912411,  0.08424196,  0.04637697, -0.1151229 , -0.41684404,
        0.25355884,  0.06032488,  0.14949498, -0.3748588 ,  0.33

In [66]:
from tqdm import tqdm
X = []
for doc in tqdm(temp_df['review'].values):
    X.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [10:12<00:00, 16.31it/s]


In [68]:
X = np.array(X)
X[0]

array([-0.16060837,  0.49697965,  0.21094511,  0.21620795, -0.09066404,
       -0.5966556 ,  0.20496441,  0.98180026, -0.3727723 , -0.28643313,
       -0.25008938, -0.4599054 ,  0.15242234,  0.15494068,  0.177519  ,
       -0.12425805,  0.01473496, -0.3177695 , -0.08079779, -0.6837773 ,
        0.03271278,  0.18842454,  0.07308728, -0.26454476, -0.3492893 ,
       -0.05273095, -0.26304245,  0.02376967, -0.2836608 ,  0.0991938 ,
        0.30097613, -0.00994897,  0.23316407, -0.30376258, -0.1666632 ,
        0.33084372,  0.0502637 , -0.33516786, -0.20764184, -0.796477  ,
        0.16537774, -0.23535657, -0.01651777, -0.08078538,  0.4233436 ,
       -0.13322029, -0.22406593, -0.0334495 ,  0.0962736 ,  0.37419188,
        0.03356032, -0.36055067, -0.46279123, -0.14789927, -0.06174221,
        0.2873573 ,  0.20386493,  0.02867124, -0.2839419 ,  0.05940871,
        0.02912411,  0.08424196,  0.04637697, -0.1151229 , -0.41684404,
        0.25355884,  0.06032488,  0.14949498, -0.3748588 ,  0.33

In [70]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7721582373560341